name: shrine
description: Learn how to use Material for structure and layout.

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  google_sign_in: ^5.2.1
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  google_fonts: ^2.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  url_launcher: ^6.0.10
  animated_text_kit: ^4.2.1
  lottie: ^1.2.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/garlic_icon.png
    - assets/default.png
